FROM apache/airflow:2.9.1

COPY --chown=airflow:root requirements.txt /tmp/requirements.txt
COPY --chown=airflow:root requirements.docker.txt /tmp/requirements.docker.txt

RUN pip install --no-cache-dir --default-timeout=1000 --retries 10 -r /tmp/requirements.docker.txt
